### ISSUE TITLE
Support Google Hangouts?

### ISSUE THREAD

**Issue by bwiernik** [matthewdias/fluidapps#2]
Is there any possibility of you preparing a similar script to support Google Hangouts at hangouts.google.com?

**Comment by matthewdias** [comment]
I've stopped using fluid in favor of Chrome apps since they're more modern and work everywhere Chrome does. I suggest you use [this](https://chrome.google.com/webstore/detail/google-hangouts/knipolnnllmklapflnccelgolnpehhpl) or [this](https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd?hl=en) instead.

**Comment by bwiernik** [comment]
I don't want to run Chrome because of its huge drag on my battery life, thanks.

**Comment by matthewdias** [comment]
I’m not going to make a hangouts script but it’s fairly simple if you want
to give it a try yourself. You can use one of the existing scripts as an
example, and modify it to react to changes in the DOM of the hangouts site.

**Comment by matthewdias** [comment]
@bwiernik if you're still looking for something, [yakyak](https://github.com/yakyak/yakyak) is great
